version: '3'

services:
    
    db:
        build:
            context: ./app/backend
            dockerfile: docker/docker_files/Dockerfile.db
            cache_from:
                - "${STAGE_DB_IMAGE}"
        image: "${STAGE_DB_IMAGE}"
        restart: unless-stopped
        env_file:
            - ./.env
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PORT= ${DB_PORT}

    app:
        restart: unless-stopped
        build:
            context: ./app/backend
            dockerfile: docker/docker_files/Dockerfile.stage
            cache_from:
                - "${STAGE_APP_IMAGE}"
        image: "${STAGE_APP_IMAGE}"

        command: gunicorn --env DJANGO_SETTINGS_MODULE=course.conf.stage course.wsgi.stage:application --bind 0.0.0.0:8000

        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
    
    redis:
        build:
            context: ./app/backend
            dockerfile: docker/docker_files/Dockerfile.redis
            cache_from:
                - "${STAGE_REDIS_IMAGE}"
        image: "${STAGE_REDIS_IMAGE}"
        restart: unless-stopped
        expose:
            - 6379
        ports:
            - "6379:6379"
            
    celery:
        restart: unless-stopped
        build:
            context: ./app/backend
            dockerfile: docker/docker_files/Dockerfile.stage
            cache_from:
                - "${STAGE_CELERY_IMAGE}"
        image: "${STAGE_CELERY_IMAGE}"
        command: celery -A course worker --loglevel=info --logfile=logs/celery.log
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
            - app


    beat:
        restart: unless-stopped
        build:
            context: ./app/backend
            dockerfile: docker/docker_files/Dockerfile.stage
            cache_from:
                - "${STAGE_BEAT_IMAGE}"
        image: "${STAGE_BEAT_IMAGE}"
        command: celery -A course beat -l info
        env_file:
            - ./.env
        depends_on:
            - db
            - redis
            - app

    nginx:
        build:
            context: ./app/backend
            dockerfile: docker/docker_files/Dockerfile.nginx
            cache_from:
                - "${STAGE_NGINX_IMAGE}"
        restart: unless-stopped
        image: "${STAGE_NGINX_IMAGE}"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app

