# Generated by Django 4.2 on 2023-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, related_name='cart_products', to='ecommerce.product', verbose_name='products'),
        ),
    ]
