# Generated by Django 4.2 on 2023-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='amount',
            field=models.FloatField(default=1.0),
        ),
    ]
